// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGGeFtLi3DWH1P4XQrjvzi7llscvOXMKQ',
    appId: '1:38103266933:web:d4a0e566b006acbe43ea3c',
    messagingSenderId: '38103266933',
    projectId: 'eastasianstudiesapplication',
    authDomain: 'eastasianstudiesapplication.firebaseapp.com',
    databaseURL: 'https://eastasianstudiesapplication-default-rtdb.firebaseio.com',
    storageBucket: 'eastasianstudiesapplication.appspot.com',
    measurementId: 'G-K10RFW3Z6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg0NCQb2JRijeM-VPRxkvwaItnKYZ32K4',
    appId: '1:38103266933:android:e3d80c89741b3bd743ea3c',
    messagingSenderId: '38103266933',
    projectId: 'eastasianstudiesapplication',
    databaseURL: 'https://eastasianstudiesapplication-default-rtdb.firebaseio.com',
    storageBucket: 'eastasianstudiesapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7AjZvT_hYp1Kbru1w5Xs0C9zE7uEvNZA',
    appId: '1:38103266933:ios:4e937e110aa09d3a43ea3c',
    messagingSenderId: '38103266933',
    projectId: 'eastasianstudiesapplication',
    databaseURL: 'https://eastasianstudiesapplication-default-rtdb.firebaseio.com',
    storageBucket: 'eastasianstudiesapplication.appspot.com',
    iosBundleId: 'com.example.ceas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7AjZvT_hYp1Kbru1w5Xs0C9zE7uEvNZA',
    appId: '1:38103266933:ios:4e937e110aa09d3a43ea3c',
    messagingSenderId: '38103266933',
    projectId: 'eastasianstudiesapplication',
    databaseURL: 'https://eastasianstudiesapplication-default-rtdb.firebaseio.com',
    storageBucket: 'eastasianstudiesapplication.appspot.com',
    iosBundleId: 'com.example.ceas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGGeFtLi3DWH1P4XQrjvzi7llscvOXMKQ',
    appId: '1:38103266933:web:d3ce33d43acd4fb643ea3c',
    messagingSenderId: '38103266933',
    projectId: 'eastasianstudiesapplication',
    authDomain: 'eastasianstudiesapplication.firebaseapp.com',
    databaseURL: 'https://eastasianstudiesapplication-default-rtdb.firebaseio.com',
    storageBucket: 'eastasianstudiesapplication.appspot.com',
    measurementId: 'G-WJYVQL04V4',
  );
}
